# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha',
        ),
        migrations.AddField(
            model_name='fechaalq',
            name='propiedad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Propiedad'),
        ),
        migrations.AddField(
            model_name='fechaalq',
            name='reserva',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Reserva'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Anfitrion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaDeReserva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='propiedad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Propiedad'),
        ),
    ]
