# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181025_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='title',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
