# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_propiedad_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='ciudad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Ciudad'),
        ),
    ]
