# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_propiedad_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechaalq',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
