# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_propiedad_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(null=True, upload_to=b'images'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tarifaDiaria',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ciudad'),
        ),
    ]
