# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181031_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='titulo',
            new_name='title',
        ),
    ]
