# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_propiedad_tarifadiaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaalq',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Reserva'),
        ),
    ]
