# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fechaalq_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaalq',
            name='propiedad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Propiedad'),
        ),
        migrations.AlterField(
            model_name='fechaalq',
            name='reserva',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Reserva'),
        ),
    ]
