# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reserva_total'),
        ('api', '0007_auto_20181026_2012'),
    ]

    operations = [
    ]
