# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181101_1837'),
        ('api', '0013_auto_20181101_1931'),
    ]

    operations = [
    ]
