# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20181102_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fechaDeReserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaDeReservaFin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaDeReservaInicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
